// THIS FILE WAS GENERATED BY yaml2dart. EDIT IS NOT RECOMMENDED.
const name = 'dloader';
const description =
    'A simple and versatile library for downloading files with support for adapters including dio, curl, wget, powershell, aria2 and axel. Feel free to create new adapters.';
const version = '1.2.7';
const repository = 'https://github.com/insign/dart_dloader';
const homepage = 'https://github.com/insign/dart_dloader';
const environment = '{sdk: >=3.9.4 <4.0.0}';
const devDependencies = '{lints: ^6.0.0, test: ^1.26.3}';
const dependencies = '{dio: ^5.9.0, executable: ^1.4.1, path: ^1.9.1}';
